// <auto-generated />
namespace Chart_ex.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class DontKnowWhy : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DontKnowWhy));
        
        string IMigrationMetadata.Id
        {
            get { return "202109300238255_DontKnowWhy"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
